def test_fail(*a, **aa):
    raise Exception("example fail")
